spring:
  datasource:
    url: jdbc:mysql://mysql.sqlpub.com:3306/ygtz_jiaowu_test
    username: sylvie233
    password: Wikdyuora4HqNZQg
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: sylvie233
  expiration: 604800
  tokenHead: Bearer
  tokenHeader: Authorization